---
- hosts: oxy

  tasks:
  - name: Installing packages on host
    apt: 
      name: ['ipset', 'netfilter-persistent', 'iptables-persistent', 'ipset-persistent']
      update_cache: yes

  - name: flush iptables ipset
    shell: |
      /usr/sbin/iptables -P INPUT ACCEPT
      /usr/sbin/ip6tables -P INPUT ACCEPT
      /usr/sbin/iptables -F INPUT
      /usr/sbin/ip6tables -F INPUT
      /usr/sbin/ip6tables -F FORWARD
      /usr/sbin/ipset flush
      /usr/sbin/ipset destroy

  - name: configuring ipset
    shell: |
      /usr/sbin/ipset create AllowedSubnetv6 hash:net family inet6 comment
      /usr/sbin/ipset add AllowedSubnetv6 {{ oxy1_v6 }}/128 comment "oxy1" 
      /usr/sbin/ipset add AllowedSubnetv6 {{ alex_v6 }}/64 comment "alex"

      /usr/sbin/ipset create AllowedSubnet hash:net comment
      /usr/sbin/ipset add AllowedSubnet {{ oxy1_v4 }}/32 comment "oxy1"
      /usr/sbin/ipset add AllowedSubnet {{ oxy2_v4 }}/32 comment "oxy2"
      /usr/sbin/ipset add AllowedSubnet {{ alex_v4 }}/32 comment "alex"  

      /usr/sbin/ipset create CIPs hash:net family inet6 comment
      /usr/sbin/ipset add CIPs {{ c1_ip_address_1 }}/128 comment "container 1 IP 1"
      /usr/sbin/ipset add CIPs {{ c1_ip_address_2 }}/128 comment "container 1 IP 2"
      /usr/sbin/ipset add CIPs {{ c1_ip_address_3 }}/128 comment "container 1 IP 3"
      /usr/sbin/ipset add CIPs {{ c1_ip_address_4 }}/128 comment "container 1 IP 4"
      /usr/sbin/ipset add CIPs {{ c2_ip_address_1 }}/128 comment "container 2 IP 1"
      /usr/sbin/ipset add CIPs {{ c2_ip_address_2 }}/128 comment "container 2 IP 2"
      /usr/sbin/ipset add CIPs {{ c2_ip_address_3 }}/128 comment "container 2 IP 3"
      /usr/sbin/ipset add CIPs {{ c2_ip_address_4 }}/128 comment "container 2 IP 4"  

  - name: configuring ip6tables (INPUT)
    shell: |
      /usr/sbin/ip6tables -F INPUT
      /usr/sbin/ip6tables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      /usr/sbin/ip6tables -A INPUT -p ipv6-icmp -m icmp6 --icmpv6-type 128 -m set --match-set AllowedSubnetv6 src -j ACCEPT
      /usr/sbin/ip6tables -A INPUT -p tcp -m tcp --dport 22 -m set --match-set AllowedSubnetv6 src -j ACCEPT
      /usr/sbin/ip6tables -A INPUT -s ::1 -d ::1 -j ACCEPT
      /usr/sbin/ip6tables -A INPUT -p icmpv6 --icmpv6-type router-advertisement -m hl --hl-eq 255 -j ACCEPT 
      /usr/sbin/ip6tables -A INPUT -p icmpv6 --icmpv6-type neighbor-solicitation -m hl --hl-eq 255 -j ACCEPT 
      /usr/sbin/ip6tables -A INPUT -p icmpv6 --icmpv6-type neighbor-advertisement -m hl --hl-eq 255 -j ACCEPT 
      /usr/sbin/ip6tables -A INPUT -p icmpv6 --icmpv6-type redirect -m hl --hl-eq 255 -j ACCEPT
      /usr/sbin/ip6tables -P INPUT DROP

  - name: configuring iptables (INPUT)
    shell: |
      /usr/sbin/iptables -F INPUT
      /usr/sbin/iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      /usr/sbin/iptables -A INPUT -p udp --dport 67:68 --sport 67:68 -j ACCEPT 
      /usr/sbin/iptables -A INPUT -p icmp -m set --match-set AllowedSubnet src -m icmp --icmp-type 8 -j ACCEPT
      /usr/sbin/iptables -A INPUT -p tcp -m set --match-set AllowedSubnet src -m tcp --dport 22 -j ACCEPT
      /usr/sbin/iptables -P INPUT DROP

  - name: Setup ip6tables (SNAT DNAT)
    shell: |
      /usr/sbin/ip6tables -t nat -F PREROUTING
      /usr/sbin/ip6tables -t nat -F POSTROUTING

      /usr/sbin/ip6tables -t nat -A PREROUTING -d {{ pub_c1_ip_address_1 }} -j DNAT --to {{ c1_ip_address_1 }}
      /usr/sbin/ip6tables -t nat -A PREROUTING -d {{ pub_c1_ip_address_2 }} -j DNAT --to {{ c1_ip_address_2 }}
      /usr/sbin/ip6tables -t nat -A PREROUTING -d {{ pub_c1_ip_address_3 }} -j DNAT --to {{ c1_ip_address_3 }}
      /usr/sbin/ip6tables -t nat -A PREROUTING -d {{ pub_c1_ip_address_4 }} -j DNAT --to {{ c1_ip_address_4 }}
      
      /usr/sbin/ip6tables -t nat -A PREROUTING -d {{ pub_c2_ip_address_1 }} -j DNAT --to {{ c2_ip_address_1 }}
      /usr/sbin/ip6tables -t nat -A PREROUTING -d {{ pub_c2_ip_address_2 }} -j DNAT --to {{ c2_ip_address_2 }}
      /usr/sbin/ip6tables -t nat -A PREROUTING -d {{ pub_c2_ip_address_3 }} -j DNAT --to {{ c2_ip_address_3 }}
      /usr/sbin/ip6tables -t nat -A PREROUTING -d {{ pub_c2_ip_address_4 }} -j DNAT --to {{ c2_ip_address_4 }}
      
      /usr/sbin/ip6tables -t nat -A POSTROUTING -s {{ c1_ip_address_1 }} -j SNAT --to {{ pub_c1_ip_address_1 }}
      /usr/sbin/ip6tables -t nat -A POSTROUTING -s {{ c1_ip_address_2 }} -j SNAT --to {{ pub_c1_ip_address_2 }}
      /usr/sbin/ip6tables -t nat -A POSTROUTING -s {{ c1_ip_address_3 }} -j SNAT --to {{ pub_c1_ip_address_3 }}
      /usr/sbin/ip6tables -t nat -A POSTROUTING -s {{ c1_ip_address_4 }} -j SNAT --to {{ pub_c1_ip_address_4 }}

      /usr/sbin/ip6tables -t nat -A POSTROUTING -s {{ c2_ip_address_1 }} -j SNAT --to {{ pub_c2_ip_address_1 }}
      /usr/sbin/ip6tables -t nat -A POSTROUTING -s {{ c2_ip_address_2 }} -j SNAT --to {{ pub_c2_ip_address_2 }}
      /usr/sbin/ip6tables -t nat -A POSTROUTING -s {{ c2_ip_address_3 }} -j SNAT --to {{ pub_c2_ip_address_3 }}
      /usr/sbin/ip6tables -t nat -A POSTROUTING -s {{ c2_ip_address_4 }} -j SNAT --to {{ pub_c2_ip_address_4 }}

  - name: configuring ip6tables (FORWARD)
    shell: |
      /usr/sbin/ip6tables -F FORWARD
      /usr/sbin/ip6tables -A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
      /usr/sbin/ip6tables -A FORWARD -p ipv6-icmp -m icmp6 --icmpv6-type 128 -m set --match-set AllowedSubnetv6 src -j ACCEPT
      /usr/sbin/ip6tables -A FORWARD -p tcp -m tcp --dport 1080 -m set --match-set AllowedSubnetv6 src -j ACCEPT
      /usr/sbin/ip6tables -A FORWARD -p tcp -m tcp --dport 3128 -m set --match-set AllowedSubnetv6 src -j ACCEPT
      /usr/sbin/ip6tables -A FORWARD -m set --match-set CIPs src -j ACCEPT
      /usr/sbin/ip6tables -P FORWARD DROP

  - name: Save fw settings
    shell: |
      /usr/sbin/netfilter-persistent save
      /usr/bin/systemctl enable netfilter-persistent
      /usr/bin/systemctl start netfilter-persistent

  - name:
    shell: |
      /usr/bin/sed -i '/net.ipv6.conf.all.forwarding=1/s/^#//g' /etc/sysctl.conf
    notify: Restart systemd-sysctl

  handlers:
  - name: Restart systemd-sysctl
    service: name=systemd-sysctl state=restarted
